### PR TITLE
Bump cert-manager API version in README

### LINKED ISSUE #46: Update cert-manager API version in README
`v1alpha2` `cert-manager` API referred to in the README [is getting deprecated](https://github.com/jetstack/cert-manager/pull/4021).

## Possible Solution

Update the example configs to use the latest `v1` API.

### PR DESCRIPTION
**Pull request by irbekrm**
Bump cert-manager API version in README

## Description

Update Readme to bump cert-manager API version to `v1`. Add a minimum
supported cert-manager version `v1` (this is the oldest `cert-manager` version that serves the `v1` API). 
Also update a few links.
Related PR https://github.com/openfaas/docs/pull/267

## Motivation and Context

- [x ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

`cert-manager` `v0.11` referred to by the README is [no longer supported](https://cert-manager.io/docs/installation/supported-releases/) and the `v1alpha2` `cert-manager` API [is getting deprecated](https://github.com/jetstack/cert-manager/pull/4021)

Fixes #46 

## How Has This Been Tested?

I've verified that the changed `Issuer` configs work and the links added to README get resolved correctly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: irbekrm <irbekrm@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the interest, this change seems fine to me, but I've asked you to fill out the additional fields on the issue template.

@Waterdrips @yankeexe related to this, what API version does arkade output? https://github.com/alexellis/arkade

@jsiebens @developer-guy what API version are we using in the inlets docs? https://github.com/inlets/docs

**Comment by irbekrm** [comment]
> @irbekrm would you like to update the OpenFaaS docs at the same time?

Thank you @alexellis - I've created a PR against docs too https://github.com/openfaas/docs/pull/267

**Comment by yankeexe** [comment]
> @Waterdrips @yankeexe related to this, what API version does arkade output? https://github.com/alexellis/arkade


@alexellis arkade has **cert-manager-v1** for both `registry_ingress_app` and `openfaas_ingres_app`. 
https://github.com/alexellis/arkade/blob/604f47c8f9c522eaef0c9e44545c426f6a58100d/cmd/apps/registry_ingress_app.go#L193
https://github.com/alexellis/arkade/blob/604f47c8f9c522eaef0c9e44545c426f6a58100d/cmd/apps/openfaas_ingress_app.go#L316

**Comment by jsiebens** [comment]
> @jsiebens @developer-guy what API version are we using in the inlets docs? https://github.com/inlets/docs

The inlets docs are already mentioning cert-manager/v1 :+1:

**Comment by alexellis** [comment]
Thanks

**Pull request merged**
