### PR TITLE
feat: support k8s 1.22 and upgrade dependencies

### LINKED ISSUE #49: Update to latest API group for Ingress to support K8s 1.22+
## Expected Behaviour

K8s < 1.22 and > 1.22 should work without changes.

## Current Behaviour

Only < 1.22 is supported due to the API group being used going away.

## List All Possible Solutions and Workarounds

Have an if statement based upon the kube API server version returned.

## Steps to Reproduce (for bugs)

1. Create a new cluster with minikube or kind using 1.22 
2. Deploy
3. Try to create FunctionIngress
4. See it fail

## Context

Must fix to continue being used on latest K8s versions.

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Mimic the `update-codegen.sh` implementation from Flagger, this implementation handles modules correctly.

- The controller code-generator is not compatible with modules and vendor, so this removes the vendor folder and all of the go flags that set the vendor mode.

- Update to client-go 0.21.3, which is the latest version with v1beta1 networking support.
- Create v1 and v2 sub-packages for the controller
  The controller package now contains all common code for the controller.

  The v1 package uses the typed client for the extensions/v1beta1 ingress
  and defines the sync handler responsible for creating and updating
  the ingress.

  The v2 package uses the typed client for the networking/v1 ingress and
  defines the the sync handler responseible for creation and updating
  the ingress.

- Add a helper function to discover the cluster capabilities and use
  this to determine which controller to start.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Resolves #49 

## How Has This Been Tested?

WIP

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Impact to existing users

None

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by LucasRoesler** [comment]
@alexellis i made the two requested changes

1. the easy one is just renaming the controller subpackages to v1beta1 and v1 to match the networking api group they use
2. re-adding the vendor folder and adding an alternative technique for installing and using code-gen. my approach mimics the approach in https://github.com/bwplotka/bingo by creating a go-submodule that depends on the correct code-gen version. This allows us to use `go mod download -modfile=...` meaning we can just use the codegen from the module cache and we don't need to invent any new tooling for fetching and managing it, it is just the native go tooling.

**Comment by LucasRoesler** [comment]
A pre-built image is available at `ghcr.io/lucasroesler/ingress-operator:pr-50`

**Comment by LucasRoesler** [comment]
I tested this in kind with k8s 1.19 using these files

```yaml
# cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 31112 # this is the NodePort created by the helm chart
    hostPort: 8080 # this is your port on localhost
    protocol: TCP
```

```yaml
# test.yaml
apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: nodeinfo
  namespace: openfaas
spec:
  domain: "nodeinfo.myfaas.club"
  function: "nodeinfo"
  ingressType: "nginx"
  path: "/v1/profiles/(.*)"
```

 and then


```sh
$ kind create cluster --config=cluster.yaml
$ arkade install openfaas \
	--basic-auth=false \
	--clusterrole \
	--ingress-operator \
	--set ingressOperator.image=ghcr.io/lucasroesler/ingress-operator:pr-50


$ faas-cli store deploy nodeinfo
$ kubectl apply -f test.yaml
$ kubectl get ing
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME       CLASS    HOSTS                  ADDRESS   PORTS   AGE
nodeinfo   <none>   nodeinfo.myfaas.club             80      5s
```

I then upgraded kind and used the latest k8s and got the same results, the ingress was created as expected

**Review by alexellis — APPROVED** [review]
LGTM, I like the simple solution of using the .tools folder. Nicely done.

**Pull request merged**
